#!/usr/bin/env python3
"""
T^3 topological flux/winding sectors of compact U(1): the exact zero-mode family.

Setting (full derivation: T3_RESULTS.md; structural layer: DERIVATION.md sec. C).
Compact U(1), charge quantum q = 1, Kogut-Susskind normalization
H = (e^2/2) int E^2 + (1/(2e^2)) int B^2, on a flat spatial 3-torus
T^3 = R^3 / Lambda, Lambda generated by a_1,a_2,a_3 with Gram matrix
G_ij = a_i . a_j, cell volume V = sqrt(det G).  Topological zero-mode sectors:

  electric winding  n in Z^3 = H^1(T^3,Z) (characters of the large gauge
    transformations, conjugate to the three Wilson-line holonomies; constant
    E = sum_i n_i a_i / V),
        E_el(n)  = (e^2/(2V)) n^T G n ;
  magnetic flux     m in Z^3 = H^2(T^3,Z) (flux 2 pi m_i through the 2-cycles;
    constant B = sum_i 2 pi m_i a_i / V),
        E_mag(m) = ((2 pi)^2/(2 e^2 V)) m^T G m .

Both labels commute with H and with each other (superselected); zero modes
decouple exactly from the photon oscillators.  In the Gibbs / torus
Hartle-Hawking family at inverse temperature beta the sector distribution is

  p(n) prop exp[-(beta e^2/(2V)) n^T G n],
  p(m) prop exp[-((2 pi)^2 beta/(2 e^2 V)) m^T G m],

the rank-b2 = 3 generalization of Donnelly-Wall arXiv:1506.05792 eq. (36):
for the rectangular torus the marginal of homology class i is the DW discrete
Gaussian with t_i = beta e^2 L_i^2 / V = e^2 Vol(B_i)/Vol(F_i)
(B_i = (x_i,tau) base 2-torus, F_i = transverse T^2 fiber: q_B^2 Vol(B) with q=1).

Modules
 A. exponential-family rank tests: electric family rank 2 (exact, all metrics);
    joint electric+magnetic family rank 3 = curved in e^2 (the obstruction).
 B. entropy-Fisher identity dS/de^2 = -e^2 I(e^2) (natural parameter linear in
    e^2), central-difference verification at all tested couplings/metrics.
 C. Fisher information: per-mode Gaussian asymptote 1/(2 e^4), total
    b2/(2 e^4) = 3/(2 e^4) for EVERY metric G (leading term shape-blind);
    geometry enters only the theta-function corrections (per-mode freeze-out at
    t_i = beta e^2 L_i^2/V ~ few); entropy constant
    S -> (3/2)[ln(2 pi/(beta e^2)) + 1] + (1/2) ln V  (shape-blind too).
 D. modular structure: Poisson duality alpha -> 4 pi^2/alpha, G -> G^{-1}
    (machine-precision check, direct vs dual evaluation); on the cubic torus
    with beta = L the magnetic family IS the Poisson dual of the electric one:
    S_tot(e^2) = S_tot(4 pi^2/e^2) exactly, self-dual point e^2 = 2 pi, where
    dS_tot/de^2 = 0 but I_tot(e^2) > 0 -- entropy stationarity without
    information loss, possible only because the joint family is curved.

Pure numpy, deterministic, no RNG.  Output: results_t3.json (next to script).
"""
import json, math, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
PI = math.pi
out = {"note": "deterministic, pure numpy, no RNG", "b2": 3}

# ---------------- 1d discrete-Gaussian machinery (diagonal metrics) ----------
def mode_arrays(t):
    """p(n) prop exp(-(t/2) n^2), n in Z."""
    nmax = int(math.sqrt(1500.0 / min(t, 1500.0))) + 12
    n = np.arange(-nmax, nmax + 1, dtype=float)
    x = -(0.5 * t) * n * n
    w = np.exp(x)            # max = 1 at n = 0
    Z = w.sum()
    return n, w / Z, Z

def mode_stats(t):
    """entropy, <n^2>, Var(n^2), ln z for one mode."""
    n, p, Z = mode_arrays(t)
    T = n * n
    ET = float((p * T).sum())
    VT = float((p * T * T).sum() - ET ** 2)
    pp = p[p > 0]
    S = float(-(pp * np.log(pp)).sum())
    return S, ET, VT, math.log(Z)

def diag_family(e2, beta, L, V):
    """Diagonal-metric electric family: t_i = beta e2 L_i^2/V.
    Returns S_tot, I(e2) = Var(R), per-mode I_i(e2), lnZ."""
    S = 0.0; I = 0.0; lnZ = 0.0; Imodes = []
    for Li in L:
        c = beta * Li * Li / V          # t_i = c * e2
        Si, ETi, VTi, lnzi = mode_stats(c * e2)
        S += Si; lnZ += lnzi
        Ii = (0.5 * c) ** 2 * VTi       # per-mode Fisher info about e2
        Imodes.append(Ii); I += Ii
    return S, I, Imodes, lnZ

# ---------------- general-metric (3d) machinery ------------------------------
def lattice_Q(G, nmax):
    """Q(n) = n^T G n on the box |n_i| <= nmax (flattened)."""
    r = np.arange(-nmax, nmax + 1)
    n1, n2, n3 = np.meshgrid(r, r, r, indexing="ij")
    N = np.stack([n1.ravel(), n2.ravel(), n3.ravel()]).astype(float)
    GN = G @ N
    return (N * GN).sum(axis=0)

def direct_stats(G, beta, e2, Q):
    """Electric family by direct lattice sum. R(n) = (beta/2V) Q(n) is the
    sufficient statistic for natural parameter e2."""
    V = math.sqrt(float(np.linalg.det(G)))
    R = (beta / (2.0 * V)) * Q
    w = np.exp(-e2 * R)                  # max = 1 at n = 0
    Z = w.sum()
    p = w / Z
    ER = float((p * R).sum())
    VR = float((p * R * R).sum() - ER ** 2)
    pp = p[p > 1e-310]
    S = float(-(pp * np.log(pp)).sum())
    return S, ER, VR, math.log(Z)

def dual_stats(G, beta, e2):
    """Same family evaluated through Poisson resummation:
    Z = (2 pi V/(beta e2))^{3/2} det(G)^{-1/2} sum_k exp(-u k^T G^{-1} k),
    u = 2 pi^2 V/(beta e2).  Exact analytic e2-derivatives of ln Z give
    <R> = -dlnZ/de2,  I(e2) = Var(R) = d2lnZ/de2^2,  S = lnZ + e2 <R>."""
    Gi = np.linalg.inv(G)
    detG = float(np.linalg.det(G))
    V = math.sqrt(detG)
    A = 2.0 * PI ** 2 * V / beta
    u = A / e2
    lam_min = float(np.linalg.eigvalsh(Gi)[0])
    kmax = max(3, int(math.sqrt(1500.0 / (u * lam_min))) + 3)
    q = lattice_Q(Gi, kmax)
    w = np.exp(-u * q)
    Th = w.sum()
    Eq = float((w * q).sum() / Th)
    Vq = float((w * q * q).sum() / Th - Eq ** 2)
    lnZ = 1.5 * math.log(2.0 * PI * V / (beta * e2)) - 0.5 * math.log(detG) \
        + math.log(Th)
    dlnZ = -1.5 / e2 + (A / e2 ** 2) * Eq
    d2lnZ = 1.5 / e2 ** 2 - 2.0 * A * Eq / e2 ** 3 + (A ** 2 / e2 ** 4) * Vq
    ER = -dlnZ
    S = lnZ + e2 * ER
    return S, ER, d2lnZ, lnZ          # d2lnZ = Var(R) = I(e2)

def svd_rank(D):
    s = np.linalg.svd(D - D[0], compute_uv=False)
    return [float(x) for x in s[:5]]

# ---------------- geometries --------------------------------------------------
GEOMS = {
    "cubic_L4":   {"L": [4.0, 4.0, 4.0], "beta": 1.0},
    "aniso_235":  {"L": [2.0, 3.0, 5.0], "beta": 1.0},
}
G_SHEAR = np.array([[4.0, 2.0, 0.0],
                    [2.0, 5.0, 2.0],
                    [0.0, 2.0, 5.0]])     # basis (2,0,0),(1,2,0),(0,1,2); V = 8
BETA_SHEAR = 1.0
V_SHEAR = math.sqrt(float(np.linalg.det(G_SHEAR)))
assert abs(V_SHEAR - 8.0) < 1e-12

# ============ Module A: exponential-family rank tests =========================
rankA = {}
for name, gm in GEOMS.items():
    L, beta = gm["L"], gm["beta"]
    V = L[0] * L[1] * L[2]
    c = [beta * Li * Li / V for Li in L]
    e2grid = np.geomspace(0.1, 8.0, 12)
    K = 6
    r = np.arange(-K, K + 1)
    n1, n2, n3 = np.meshgrid(r, r, r, indexing="ij")
    nsq = [n1.ravel() ** 2, n2.ravel() ** 2, n3.ravel() ** 2]
    rows = []
    for e2 in e2grid:
        lnp = np.zeros(nsq[0].size)
        for i in range(3):
            t = c[i] * e2
            lnz = mode_stats(t)[3]
            lnp += -(0.5 * t) * nsq[i] - lnz
        rows.append(lnp)
    s = svd_rank(np.array(rows))
    rankA[name] = {"singular_values": s, "sigma3_over_sigma2": s[2] / s[1]}

# sheared metric: lnZ from direct sums on a moderate-coupling grid
e2grid_sh = np.geomspace(1.5, 4.0, 8)
lam_min_G = float(np.linalg.eigvalsh(G_SHEAR)[0])
alpha_min = BETA_SHEAR * e2grid_sh[0] / V_SHEAR
nmax_sh = int(math.sqrt(3000.0 / (alpha_min * lam_min_G))) + 4
Q_SH = lattice_Q(G_SHEAR, nmax_sh)
K = 5
r = np.arange(-K, K + 1)
n1, n2, n3 = np.meshgrid(r, r, r, indexing="ij")
NS = np.stack([n1.ravel(), n2.ravel(), n3.ravel()]).astype(float)
Qsmall = (NS * (G_SHEAR @ NS)).sum(axis=0)
rows = []
for e2 in e2grid_sh:
    lnZ = direct_stats(G_SHEAR, BETA_SHEAR, e2, Q_SH)[3]
    rows.append(-(BETA_SHEAR * e2 / (2.0 * V_SHEAR)) * Qsmall - lnZ)
s = svd_rank(np.array(rows))
rankA["sheared_V8"] = {"singular_values": s, "sigma3_over_sigma2": s[2] / s[1],
                       "nmax_direct": nmax_sh}
out["A_rank_tests_electric"] = rankA

# ============ Module B: entropy-Fisher identity ================================
def identity_row_diag(L, beta, e2):
    V = L[0] * L[1] * L[2]
    S, I, Imodes, _ = diag_family(e2, beta, L, V)
    d = 1e-6 * e2
    Sp = diag_family(e2 + d, beta, L, V)[0]
    Sm = diag_family(e2 - d, beta, L, V)[0]
    dS = (Sp - Sm) / (2 * d)
    res = abs(dS + e2 * I) / max(abs(dS), 1e-300)
    return S, I, dS, res

identB = {}
for name, gm in GEOMS.items():
    rows = []
    for e2 in [0.05, 0.1, 0.2, 0.4, 0.8, 1.5, 3.0, 6.0, 12.0]:
        S, I, dS, res = identity_row_diag(gm["L"], gm["beta"], e2)
        rows.append({"e2": e2, "S": S, "I_e2": I, "dS_de2": dS,
                     "identity_relres": res})
    identB[name] = rows
rows = []
for e2 in [1.5, 2.5, 4.0]:
    S, ER, VR, _ = direct_stats(G_SHEAR, BETA_SHEAR, e2, Q_SH)
    d = 1e-6 * e2
    Sp = direct_stats(G_SHEAR, BETA_SHEAR, e2 + d, Q_SH)[0]
    Sm = direct_stats(G_SHEAR, BETA_SHEAR, e2 - d, Q_SH)[0]
    dS = (Sp - Sm) / (2 * d)
    rows.append({"e2": e2, "S": S, "I_e2": VR, "dS_de2": dS,
                 "identity_relres": abs(dS + e2 * VR) / abs(dS)})
identB["sheared_V8"] = rows
out["B_entropy_fisher_identity"] = identB

# ============ Module C: Fisher information and entropy asymptotics ============
fisherC = {}
for name, gm in GEOMS.items():
    L, beta = gm["L"], gm["beta"]
    V = L[0] * L[1] * L[2]
    rows = []
    for e2 in [0.05, 0.1, 0.2, 0.4, 0.8, 1.5, 3.0, 6.0, 12.0]:
        S, I, Imodes, _ = diag_family(e2, beta, L, V)
        t = [beta * Li * Li / V * e2 for Li in L]
        rows.append({
            "e2": e2, "t_modes": t, "S": S, "I_e2": I,
            "I_times_2e4_over_b2": I * 2.0 * e2 ** 2 / 3.0,
            "per_mode_I_times_2e4": [Ii * 2.0 * e2 ** 2 for Ii in Imodes],
            "S_minus_asymptote": S - (1.5 * (math.log(2.0 * PI / (beta * e2)) + 1.0)
                                      + 0.5 * math.log(V)),
        })
    fisherC[name] = rows
# sheared: weak coupling via dual representation, moderate via direct
rows = []
for e2, how in [(0.05, "dual"), (0.1, "dual"), (0.2, "dual"), (0.4, "dual"),
                (1.5, "direct"), (2.5, "direct"), (4.0, "direct")]:
    if how == "dual":
        S, ER, I, lnZ = dual_stats(G_SHEAR, BETA_SHEAR, e2)
    else:
        S, ER, I, lnZ = direct_stats(G_SHEAR, BETA_SHEAR, e2, Q_SH)
    rows.append({
        "e2": e2, "method": how, "S": S, "I_e2": I,
        "I_times_2e4_over_b2": I * 2.0 * e2 ** 2 / 3.0,
        "S_minus_asymptote": S - (1.5 * (math.log(2.0 * PI / (BETA_SHEAR * e2)) + 1.0)
                                  + 0.5 * math.log(V_SHEAR)),
    })
fisherC["sheared_V8"] = rows
out["C_fisher_and_entropy"] = fisherC

# per-mode crossover curve: 2 e^4 I_mode as a function of t (geometry-collapsed);
# 2 e^4 I_mode = 2 e^4 (c/2)^2 Var(n^2) = (t^2/2) Var_t(n^2)  (since t = c e2)
curve = []
for t in [0.05, 0.2, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 5.5, 6.0, 8.0, 12.0]:
    _, _, VT, _ = mode_stats(t)
    curve.append({"t": t, "two_e4_I_mode": 0.5 * t * t * VT})
out["C_per_mode_crossover_curve"] = curve
out["C_notes"] = {
    "leading": "I(e2) -> b2/(2 e^4) for every metric G (trace identity; b2 = 3)",
    "per_mode": "2 e^4 I_mode = (t^2/2) Var_t(n^2): -> 1 as t -> 0, single peak ~1.53 near t ~ 5, ~exp(-t/2) collapse beyond (freeze-out); geometry fixes each mode's position on this one curve via t_i = beta e2 L_i^2/V",
    "entropy": "S -> (b2/2)[ln(2 pi/(beta e2)) + 1] + (1/2) ln V: shape-blind, volume only",
}

# ============ Module D: modular structure / duality ===========================
modD = {}
# (i) direct vs Poisson-dual evaluation, sheared metric (the modular identity)
rows = []
for e2 in [1.5, 2.5, 4.0]:
    Sd, ERd, Id, lnZd = direct_stats(G_SHEAR, BETA_SHEAR, e2, Q_SH)
    Sp, ERp, Ip, lnZp = dual_stats(G_SHEAR, BETA_SHEAR, e2)
    rows.append({"e2": e2,
                 "lnZ_direct_minus_dual": lnZd - lnZp,
                 "S_direct_minus_dual": Sd - Sp,
                 "I_direct_minus_dual_rel": (Id - Ip) / Id})
modD["poisson_identity_sheared"] = rows
# (ii) cubic torus, beta = L: t_E = e2, t_M = 4 pi^2/e2 exactly per mode
Lc, betac = 4.0, 4.0
Vc = Lc ** 3
cc = betac * Lc * Lc / Vc
assert abs(cc - 1.0) < 1e-15
def joint_stats(e2):
    tE = e2
    tM = 4.0 * PI ** 2 / e2
    SE, ETE, VTE, _ = mode_stats(tE)
    SM, ETM, VTM, _ = mode_stats(tM)
    S_tot = 3.0 * (SE + SM)
    I_E = 3.0 * 0.25 * VTE                       # (c/2)^2 Var(n^2), c = 1
    I_M = 3.0 * (2.0 * PI ** 2 / e2 ** 2) ** 2 * VTM
    return S_tot, I_E, I_M
rows = []
for e2 in [1.0, 2.0, PI, 4.0]:
    S1 = joint_stats(e2)[0]
    S2 = joint_stats(4.0 * PI ** 2 / e2)[0]
    rows.append({"e2": e2, "dual_e2": 4.0 * PI ** 2 / e2,
                 "S_tot": S1, "S_tot_dual": S2, "diff": S1 - S2})
modD["selfduality_S_tot"] = rows
# self-dual point: dS_tot/de2 = 0, I_tot > 0
e2sd = 2.0 * PI
d = 1e-6 * e2sd
Ssd, IE, IM = joint_stats(e2sd)
Sp = joint_stats(e2sd + d)[0]
Sm = joint_stats(e2sd - d)[0]
dS_sd = (Sp - Sm) / (2 * d)
modD["self_dual_point"] = {
    "e2": e2sd, "S_tot": Ssd, "dS_de2": dS_sd,
    "I_E": IE, "I_M": IM, "I_tot": IE + IM,
    "minus_e2_I_tot": -e2sd * (IE + IM),
}
# identity-ratio sweep for the joint (curved) family
rows = []
for e2 in [0.3, 1.0, 2.0, PI, 5.0, e2sd, 8.0, 12.0, 25.0, 60.0]:
    S0, IE, IM = joint_stats(e2)
    d = 1e-6 * e2
    Sp = joint_stats(e2 + d)[0]
    Sm = joint_stats(e2 - d)[0]
    dS = (Sp - Sm) / (2 * d)
    rows.append({"e2": e2, "S_tot": S0, "I_tot": IE + IM,
                 "ratio_dS_over_minus_e2I": dS / (-e2 * (IE + IM))})
modD["joint_identity_ratio"] = rows
# joint rank test (single homology class, (n,m) pairs): rank 3, curved
K = 12
nv = np.arange(-K, K + 1, dtype=float)
N2, M2 = np.meshgrid(nv ** 2, nv ** 2, indexing="ij")
rows = []
for e2 in np.geomspace(1.0, 40.0, 12):
    tE, tM = e2, 4.0 * PI ** 2 / e2
    lnzE = mode_stats(tE)[3]
    lnzM = mode_stats(tM)[3]
    rows.append((-(0.5 * tE) * N2 - (0.5 * tM) * M2).ravel() - lnzE - lnzM)
s = svd_rank(np.array(rows))
# electric-only control on the identical coupling grid and config set
rowsE = []
for e2 in np.geomspace(1.0, 40.0, 12):
    lnzE = mode_stats(e2)[3]
    rowsE.append((-(0.5 * e2) * N2 + 0.0 * M2).ravel() - lnzE)
sE = svd_rank(np.array(rowsE))
modD["joint_rank_test"] = {"singular_values": s,
                           "sigma3_over_sigma2": s[2] / s[1],
                           "sigma4_over_sigma3": s[3] / s[2],
                           "sigma3_abs": s[2],
                           "electric_control_same_grid_sv": sE,
                           "note": "joint family: sigma3 = O(1) (rank 3, curved curve (theta_E, theta_M) = (e2, 4 pi^2/e2)); electric control: sigma3 = O(1e-12) (exact rank-2 exponential family)"}
out["D_modular_duality"] = modD

# DW dictionary record (rectangular torus)
out["DW_dictionary"] = {
    "statement": "marginal of class i = DW 1506.05792 eq.(36) with t_i = beta e2 L_i^2/V = e2 Vol(B_i)/Vol(F_i), B_i = (x_i,tau) torus (Vol = beta L_i), F_i = transverse T^2 (Vol = V/L_i); q = 1",
    "aniso_235_beta1_e2_1": [
        {"i": i, "t_from_L2_over_V": Li * Li / 30.0,
         "t_from_VolB_over_VolF": (1.0 * Li) / (30.0 / Li)}
        for i, Li in enumerate([2.0, 3.0, 5.0])
    ],
}

with open(os.path.join(HERE, "results_t3.json"), "w") as f:
    json.dump(out, f, indent=1)

# ---------------- console summary ---------------------------------------------
print("=== A: electric-family rank tests (sigma3/sigma2; exact family -> 0) ===")
for k, v in rankA.items():
    print("  %-12s sigma3/sigma2 = %.3e" % (k, v["sigma3_over_sigma2"]))
print("=== B: dS/de2 = -e2 I(e2) relative residuals ===")
for k, v in identB.items():
    worst = max(r["identity_relres"] for r in v)
    print("  %-12s worst relres = %.3e" % (k, worst))
print("=== C: I(e2) * 2e4 / b2 (-> 1) and entropy asymptote residual ===")
for k, v in fisherC.items():
    r0 = v[0]
    print("  %-12s e2=%.2f  2e4*I/b2 = %.12f  S-asymptote = %.3e"
          % (k, r0["e2"], r0["I_times_2e4_over_b2"], r0["S_minus_asymptote"]))
print("=== D: modular/duality ===")
for r in modD["poisson_identity_sheared"]:
    print("  Poisson identity (sheared) e2=%.1f: dlnZ = %.3e" % (r["e2"], r["lnZ_direct_minus_dual"]))
for r in modD["selfduality_S_tot"]:
    print("  S_tot(e2=%.4f) - S_tot(4pi^2/e2) = %.3e" % (r["e2"], r["diff"]))
sd = modD["self_dual_point"]
print("  self-dual e2 = 2 pi: dS/de2 = %.3e, I_tot = %.6f, -e2 I_tot = %.4f"
      % (sd["dS_de2"], sd["I_tot"], sd["minus_e2_I_tot"]))
jr = modD["joint_rank_test"]
print("  joint rank test: sigma3 = %.3f (curved, rank 3; s4/s3 = %.1e); electric control sigma3 = %.1e"
      % (jr["sigma3_abs"], jr["sigma4_over_sigma3"], jr["electric_control_same_grid_sv"][2]))
print("\nsaved results_t3.json")
